//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Student
    {
        [Required(ErrorMessage = "Ожидается")]
        [Range(0,10000000)]
        public int RecordBook { get; set; }
        public string Group_2_Cipher { get; set; }
        [Required]
        [Range(0, 10000000)]
        public Nullable<int> FatherSalary { get; set; }
        [Required]
        [Range(0, 10000000)]
        public Nullable<int> MotherSalary { get; set; }
        [Required(ErrorMessage = "Ожидается")]
        public string FullName { get; set; }
        [Required]
        [Range(0, 10)]
        public Nullable<byte> Family { get; set; }
    
        public virtual Group_2 Group_2 { get; set; }
    }
}
